### ISSUE TITLE
Booster can cache false positive results for non-ready-for-rendering pages?

### ISSUE THREAD

**Issue by vbradnitski** [enonic/app-booster#60]
An interesting corner case could be related to booster: https://enonic.zendesk.com/agent/tickets/7585

Booster app is used together with React4XP in a cluster environment. After an iterative restart of the frontend nodes, we got a state when XP returned an empty/almost empty page with 200 status for one particular site. 
We restarted the booster app from the application app + customer turned off and on the app on this site directly. 
Since it helped, it's assumed it can be a booster case.

**Comment by rymsha** [comment]
This happens due to https://github.com/enonic/xp/issues/10682
Can't be fixed ib Booster. Should be fixed in XP
